// Generated by CoffeeScript 1.3.3
(function() {

  describe("Templates", function() {
    return describe('when a template is recieved', function() {
      it("doesn't call the callback when there are templates remaining.", function() {
        Templates.templatesToLoad = [
          {
            name: 'template-name'
          }, {
            name: 'template-name2'
          }
        ];
        Templates.successFn({
          templates: {}
        }, Templates.templatesToLoad[0])();
        return expect(Templates.areTemplatesLoaded()).toBe(false);
      });
      return it("calls the callback when there are no templates remaining.", function() {
        Templates.templatesToLoad = [
          {
            name: 'template-name'
          }
        ];
        spyOn(Templates, 'templatesLoaded');
        Templates.successFn({
          templates: {}
        }, Templates.templatesToLoad[0])();
        return expect(Templates.templatesLoaded).toHaveBeenCalled();
      });
    });
  });

}).call(this);
